In [1]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\chira\anaconda3\lib\site-packages (1.6.2)
Requirement already satisfied: scipy in c:\users\chira\anaconda3\lib\site-packages (from xgboost) (1.7.1)
Requirement already satisfied: numpy in c:\users\chira\anaconda3\lib\site-packages (from xgboost) (1.20.3)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install scikit-optimize

Requirement already satisfied: scikit-optimize in c:\users\chira\anaconda3\lib\site-packages (0.9.0)
Requirement already satisfied: scipy>=0.19.1 in c:\users\chira\anaconda3\lib\site-packages (from scikit-optimize) (1.7.1)
Requirement already satisfied: pyaml>=16.9 in c:\users\chira\anaconda3\lib\site-packages (from scikit-optimize) (21.10.1)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\chira\anaconda3\lib\site-packages (from scikit-optimize) (0.24.2)
Requirement already satisfied: numpy>=1.13.3 in c:\users\chira\anaconda3\lib\site-packages (from scikit-optimize) (1.20.3)
Requirement already satisfied: joblib>=0.11 in c:\users\chira\anaconda3\lib\site-packages (from scikit-optimize) (1.1.0)
Requirement already satisfied: PyYAML in c:\users\chira\anaconda3\lib\site-packages (from pyaml>=16.9->scikit-optimize) (6.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\chira\anaconda3\lib\site-packages (from scikit-learn>=0.20.0->scikit-optimize) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [36]:
# 1.0 Clear ipython memory
#%reset -f

# 1.1 Data manipulation and plotting modules
import numpy as np
import pandas as pd


# 1.2 Data pre-processing
#     z = (x-mean)/stdev
from sklearn.preprocessing import StandardScaler as ss

# 1.3 Dimensionality reduction and noise removal
from sklearn.decomposition import PCA

# 1.4 Data splitting and model parameter search
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

# 1.5 Model pipelining
from sklearn.pipeline import Pipeline
from sklearn.pipeline import make_pipeline

# 1.6 Hyperparameter optimization
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

# 1.7.1
#     pip install scikit-optimize
#     pip install 'scikit-optimize[plots]'
#     Refer: https://github.com/scikit-optimize/scikit-optimize
#     conda install -c conda-forge scikit-optimize
from skopt import BayesSearchCV 
from skopt.space import Real, Categorical, Integer

# 1.8 Modeling modules
#     Call sklearn wrapper of xgboost
# """Scikit-Learn Wrapper interface for XGBoost."""
#  """Implementation of the Scikit-Learn API for XGBoost.
# https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn
# Stackoverflow:
# https://stackoverflow.com/a/34696477
# https://stackoverflow.com/a/46947191
# Install as: conda install -c anaconda py-xgboost
from xgboost.sklearn import XGBClassifier
from sklearn.preprocessing import LabelEncoder

In [4]:
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
from sklearn.preprocessing import StandardScaler

In [5]:
# 1.9 Model evaluation metrics
from sklearn.metrics import accuracy_score, f1_score
from sklearn.metrics import plot_roc_curve
from sklearn.metrics import confusion_matrix

# 1.10
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import plot_importance

# 1.11 Permutation feature importance
from sklearn.inspection import permutation_importance

In [6]:
# 1.12 Misc
import time
import os
import gc
import random

# 1.13 Used in Randomized parameter search
from scipy.stats import uniform

In [7]:
# 1.14
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [8]:
# 1.15 Set option to dislay many rows
pd.set_option('display.max_columns', 100)

In [125]:
y_train1.head()

1032044    No
565990     No
1574387    No
849646     No
616799     No
Name: went_on_backorder, dtype: object

In [129]:
y_train.head()

1550483    No
785453     No
476946     No
1132095    No
474487     No
Name: went_on_backorder, dtype: object

In [119]:
y_train1 = df_train["went_on_backorder"]

In [132]:
df_train['went_on_backorder'] = le.fit_transform(df_train['went_on_backorder'])

In [133]:
df_train.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,0
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,0.99,0.99,0.0,No,No,No,Yes,No,0
2,1043696,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,0
3,1043852,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,No,0.0,0.10,0.13,0.0,No,No,No,Yes,No,0
4,1044048,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,0

In [130]:
df_train = pd.read_csv("C:/Users/chira/Desktop/BDDA Assignment/Back_order_train.csv")
df_test = pd.read_csv("C:/Users/chira/Desktop/BDDA Assignment/Back_order_test.csv")

C:\Users\chira\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [11]:
print("\n Shape")
df_train.shape                # 100039, 33)
print("\n\n Columns")
df_train.columns.values       # Label column is the last one
print("\n")

# 3.0.1
print("\n\nTarget distribution")
df_train.value_counts()  # Classes are not unbalanced
                           # Binary data
                           #  b: 65558 , s: 34242
# 3.0.2
print("\n\nData types")                        
df_train.dtypes.value_counts()  # Label column is of object type
print("\n")
df_train.head()

 Shape

(1687861, 23)

 Columns

array(['sku', 'national_inv', 'lead_time', 'in_transit_qty',
       'forecast_3_month', 'forecast_6_month', 'forecast_9_month',
       'sales_1_month', 'sales_3_month', 'sales_6_month', 'sales_9_month',
       'min_bank', 'potential_issue', 'pieces_past_due',
       'perf_6_month_avg', 'perf_12_month_avg', 'local_bo_qty',
       'deck_risk', 'oe_constraint', 'ppap_risk', 'stop_auto_buy',
       'rev_stop', 'went_on_backorder'], dtype=object)

Target distribution

sku      national_inv  lead_time  in_transit_qty  forecast_3_month  forecast_6_month  forecast_9_month  sales_1_month  sales_3_month  sales_6_month  sales_9_month  min_bank  potential_issue  pieces_past_due  perf_6_month_avg  perf_12_month_avg  local_bo_qty  deck_risk  oe_constraint  ppap_risk  stop_auto_buy  rev_stop  went_on_backorder
1043384  2.0           9.0        0.0             0.0               0.0               0.0               0.0            0.0            0.0            0.0            0.0       No               0.0              0.99              0.99               0.0           No         No             No         Yes            No        No                   1
2239854  45.0          52.0       0.0             0.0               0.0               0.0               1.0            3.0            4.0            8.0            0.0       No               0.0              0.63              0.75               0.0           Yes        No             No         Yes            No        No                   1
2239827  7.0           8.0        0.0             0.0               0.0               0.0               0.0            0.0            0.0            0.0            2.0       No               0.0              0.97              0.90               0.0           No         No             No         Yes            No        No                   1
2239826  0.0           8.0        1.0             1.0               2.0               3.0               0.0            2.0            2.0            3.0            0.0       No               0.0              0.98              0.97               0.0           No         No             No         Yes            No        No                   1
2239825  19.0          8.0        0.0             0.0               0.0               0.0               0.0            0.0            0.0            0.0            1.0       No               0.0              0.93              0.96               0.0           No         No             No         Yes            No        No                   1
                                                                                                                                                                                                                                                                                                                                                     ..
1677162  2208.0        2.0        0.0             0.0               0.0               0.0               47.0           139.0          263.0          360.0          49.0      No               0.0              1.00              0.99               0.0           No         No             No         Yes            No        No                   1
1677161  3.0           2.0        0.0             24.0              48.0              72.0              11.0           28.0           44.0           67.0           0.0       No               0.0              0.98              0.97               0.0           No         No             No         Yes            No        Yes                  1
1677160  0.0           4.0        0.0             0.0               0.0               0.0               0.0            0.0            0.0            0.0            0.0       No               0.0              0.96              0.97               0.0           Yes        No             No         No             No        No                   1
1677159  51.0          8.0        0.0             22.0              66.0              88.0              6.0            16.0           30.0           56.0           4.0       No               0.0              0.79              0.80               0.0           No         No             No         Yes            No        No                   1
3284919  10.0          12.0       1.0             0.0               0.0               0.0               0.0            0.0            0.0            0.0            1.0       No               0.0              0.48              0.48               0.0           Yes        No             No         Yes            No        No                   1
Length: 1586967, dtype: int64

Data types

float64    15
object      8
dtype: int64

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No,No
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,0.99,0.99,0.0,No,No,No,Yes,No,No
2,1043696,2.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No
3,1043852,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,No,0.0,0.10,0.13,0.0,No,No,No,Yes,No,No
4,1044048,8.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,No,0.0,-99.00,-99.00,0.0,Yes,No,No,Yes,No,No

In [12]:
df_train.shape

(1687861, 23)

In [13]:
df_train.describe()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty
count,1.687860e+06,1.586967e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06,1.687860e+06
mean,4.961118e+02,7.872267e+00,4.405202e+01,1.781193e+02,3.449867e+02,5.063644e+02,5.592607e+01,1.750259e+02,3.417288e+02,5.252697e+02,5.277230e+01,2.043724e+00,-6.872059e+00,-6.437947e+00,6.264507e-01
std,2.961523e+04,7.056024e+00,1.342742e+03,5.026553e+03,9.795152e+03,1.437892e+04,1.928196e+03,5.192378e+03,9.613167e+03,1.483861e+04,1.254983e+03,2.360165e+02,2.655636e+01,2.584333e+01,3.372224e+01
min,-2.725600e+04,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-9.900000e+01,-9.900000e+01,0.000000e+00
25%,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.300000e-01,6.600000e-01,0.000000e+00
50%,1.500000e+01,8.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,8.200000e-01,8.100000e-01,0.000000e+00
75%,8.000000e+01,9.000000e+00,0.000000e+00,4.000000e+00,1.200000e+01,2.000000e+01,4.000000e+00,1.500000e+01,3.100000e+01,4.700000e+01,3.000000e+00,0.000000e+00,9.700000e-01,9.500000e-01,0.000000e+00
max,1.233440e+07,5.200000e+01,4.894080e+05,1.427612e+06,2.461360e+06,3.777304e+06,7.417740e+05,1.105478e+06,2.146625e+06,3.205172e+06,3.133190e+05,1.464960e+05,1.000000e+00,1.000000e+00,1.253000e+04

In [14]:
df_train = df_train.dropna(axis=0)

In [15]:
df_train.shape

(1586967, 23)

In [160]:
X = df_train.iloc [ : ,0:22]
X.head(2)

y = df_train.iloc [:,22]
y.head(2)

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
0,1026827,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,No,No,No,Yes,No
1,1043384,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,0.99,0.99,0.0,No,No,No,Yes,No

0    0
1    0
Name: went_on_backorder, dtype: int32

In [37]:
le = LabelEncoder()

In [49]:
df_train['deck_risk'] = le.fit_transform(df_train['deck_risk'])
df_train['potential_issue'] = le.fit_transform(df_train['potential_issue'])
df_train['oe_constraint'] = le.fit_transform(df_train['oe_constraint'])
df_train['ppap_risk'] = le.fit_transform(df_train['ppap_risk'])
df_train['rev_stop'] = le.fit_transform(df_train['rev_stop'])

df_train['stop_auto_buy'] = le.fit_transform(df_train['stop_auto_buy'])
df_train['went_on_backorder'] = le.fit_transform(df_train['went_on_backorder'])

In [56]:
df_train = df_train.drop('sku',axis=1)

In [79]:
df_train.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop,went_on_backorder
1,2.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.99,0.99,0.0,0,0,0,1,0,0
3,7.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,0.0,0.10,0.13,0.0,0,0,0,1,0,0
5,13.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.82,0.87,0.0,0,0,0,1,0,0
7,6.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.00,0.00,0.0,1,0,1,1,0,0
9,4.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.82,0.87,0.0,0,0,0,1,0,0

In [135]:
y_train.head()

1550483    No
785453     No
476946     No
1132095    No
474487     No
Name: went_on_backorder, dtype: object

In [170]:
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.35,
                                                    shuffle = True,
                                                  
                                                    )

# 4.1
X_train.shape        # (65025, 30)
X_test.shape         # (35014, 30)
y_train.shape        # (65025,)
y_test.shape         # (35014,)

(1097109, 22)

(590752, 22)

(1097109,)

(590752,)

In [171]:
y_train.head()

1147617    0
672642     0
656320     0
1398417    0
386956     0
Name: went_on_backorder, dtype: int32

In [113]:
y_train.head()

1550483    No
785453     No
476946     No
1132095    No
474487     No
Name: went_on_backorder, dtype: object

In [103]:
y_train.unique()

array(['No', 'Yes'], dtype=object)

In [101]:
X_train.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
1550483,116.0,8.0,16.0,77.0,191.0,305.0,18.0,69.0,161.0,265.0,57.0,0,0.0,0.88,0.91,0.0,0,0,0,1,0
785453,24.0,4.0,0.0,0.0,0.0,0.0,3.0,8.0,14.0,30.0,3.0,0,0.0,0.73,0.78,0.0,0,0,0,1,0
476946,112.0,8.0,3.0,0.0,12.0,49.0,14.0,45.0,111.0,159.0,18.0,0,0.0,0.99,0.99,0.0,0,0,0,1,0
1132095,2.0,8.0,0.0,1.0,2.0,3.0,1.0,1.0,1.0,2.0,0.0,0,0.0,0.82,0.75,0.0,0,0,0,1,0
474487,36.0,16.0,0.0,0.0,0.0,20.0,4.0,16.0,28.0,51.0,0.0,0,0.0,0.38,0.44,0.0,0,0,0,1,0

In [86]:
X_train['deck_risk'] = le.fit_transform(X_train['deck_risk'])
X_train['potential_issue'] = le.fit_transform(X_train['potential_issue'])
X_train['oe_constraint'] = le.fit_transform(X_train['oe_constraint'])
X_train['ppap_risk'] = le.fit_transform(X_train['ppap_risk'])
X_train['rev_stop'] = le.fit_transform(X_train['rev_stop'])

X_train['stop_auto_buy'] = le.fit_transform(X_train['stop_auto_buy'])

C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['deck_risk'] = le.fit_transform(X_train['deck_risk'])
C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['potential_issue'] = le.fit_transform(X_train['potential_issue'])
C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['oe_constraint'] = le.fit_transform(X_train['oe_constraint'])
C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['ppap_risk'] = le.fit_transform(X_train['ppap_risk'])
C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['rev_stop'] = le.fit_transform(X_train['rev_stop'])
C:\Users\chira\AppData\Local\Temp/ipykernel_25300/468936761.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['stop_auto_buy'] = le.fit_transform(X_train['stop_auto_buy'])

In [88]:
X_train = X_train.drop('sku',axis=1)

In [172]:
steps_xg = [('sts', ss() ),
            ('pca', PCA()),
            ('xg',  XGBClassifier(silent = False,
                                  n_jobs=3)        # Specify other parameters here
            )
            ]

# 5.1  Instantiate Pipeline object

pipe_xg = Pipeline(steps_xg)

In [173]:
pipe_xg.get_params()

{'memory': None,
 'steps': [('sts', StandardScaler()),
  ('pca', PCA()),
  ('xg',
   XGBClassifier(base_score=None, booster=None, callbacks=None,
                 colsample_bylevel=None, colsample_bynode=None,
                 colsample_bytree=None, early_stopping_rounds=None,
                 enable_categorical=False, eval_metric=None, gamma=None,
                 gpu_id=None, grow_policy=None, importance_type=None,
                 interaction_constraints=None, learning_rate=None, max_bin=None,
                 max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
                 max_leaves=None, min_child_weight=None, missing=nan,
                 monotone_constraints=None, n_estimators=100, n_jobs=3,
                 num_parallel_tree=None, predictor=None, random_state=None,
                 reg_alpha=None, reg_lambda=None, ...))],
 'verbose': False,
 'sts': StandardScaler(),
 'pca': PCA(),
 'xg': XGBClassifier(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bynode=None,
               colsample_bytree=None, early_stopping_rounds=None,
               enable_categorical=False, eval_metric=None, gamma=None,
               gpu_id=None, grow_policy=None, importance_type=None,
               interaction_constraints=None, learning_rate=None, max_bin=None,
               max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
               max_leaves=None, min_child_weight=None, missing=nan,
               monotone_constraints=None, n_estimators=100, n_jobs=3,
               num_parallel_tree=None, predictor=None, random_state=None,
               reg_alpha=None, reg_lambda=None, ...),
 'sts__copy': True,
 'sts__with_mean': True,
 'sts__with_std': True,
 'pca__copy': True,
 'pca__iterated_power': 'auto',
 'pca__n_components': None,
 'pca__random_state': None,
 'pca__svd_solver': 'auto',
 'pca__tol': 0.0,
 'pca__whiten': False,
 'xg__objective': 'binary:logistic',
 'xg__use_label_encoder': False,
 'xg__base_score': None,
 'xg__booster': None,
 'xg__callbacks': None,
 'xg__colsample_bylevel': None,
 'xg__colsample_bynode': None,
 'xg__colsample_bytree': None,
 'xg__early_stopping_rounds': None,
 'xg__enable_categorical': False,
 'xg__eval_metric': None,
 'xg__gamma': None,
 'xg__gpu_id': None,
 'xg__grow_policy': None,
 'xg__importance_type': None,
 'xg__interaction_constraints': None,
 'xg__learning_rate': None,
 'xg__max_bin': None,
 'xg__max_cat_to_onehot': None,
 'xg__max_delta_step': None,
 'xg__max_depth': None,
 'xg__max_leaves': None,
 'xg__min_child_weight': None,
 'xg__missing': nan,
 'xg__monotone_constraints': None,
 'xg__n_estimators': 100,
 'xg__n_jobs': 3,
 'xg__num_parallel_tree': None,
 'xg__predictor': None,
 'xg__random_state': None,
 'xg__reg_alpha': None,
 'xg__reg_lambda': None,
 'xg__sampling_method': None,
 'xg__scale_pos_weight': None,
 'xg__subsample': None,
 'xg__tree_method': None,
 'xg__validate_parameters': None,
 'xg__verbosity': None,
 'xg__silent': False}

In [174]:
parameters = {'xg__learning_rate':  [0.03, 0.05], # learning rate decides what percentage
                                                  #  of error is to be fitted by
                                                  #   by next boosted tree.
                                                  # See this answer in stackoverflow:
                                                  # https://stats.stackexchange.com/questions/354484/why-does-xgboost-have-a-learning-rate
                                                  # Coefficients of boosted trees decide,
                                                  #  in the overall model or scheme, how much importance
                                                  #   each boosted tree shall have. Values of these
                                                  #    Coefficients are calculated by modeling
                                                  #     algorithm and unlike learning rate are
                                                  #      not hyperparameters. These Coefficients
                                                  #       get adjusted by l1 and l2 parameters
              'xg__n_estimators':   [200,  300],  # Number of boosted trees to fit
                                                  # l1 and l2 specifications will change
                                                  # the values of coeff of boosted trees
                                                  # but not their numbers

              'xg__max_depth':      [4,6],
              'pca__n_components' : [18,24],
              'xg__booster': ['gbtree','gblinear']
              }

In [175]:
parameters = {'xg__learning_rate':  [0.03, 0.05], # learning rate decides what percentage
                                                  #  of error is to be fitted by
                                                  #   by next boosted tree.
                                                  # See this answer in stackoverflow:
                                                  # https://stats.stackexchange.com/questions/354484/why-does-xgboost-have-a-learning-rate
                                                  # Coefficients of boosted trees decide,
                                                  #  in the overall model or scheme, how much importance
                                                  #   each boosted tree shall have. Values of these
                                                  #    Coefficients are calculated by modeling
                                                  #     algorithm and unlike learning rate are
                                                  #      not hyperparameters. These Coefficients
                                                  #       get adjusted by l1 and l2 parameters
               'xg__max_depth':      [4,6],
 
              'pca__n_components' : [18,24],
               }

In [176]:
clf = GridSearchCV(pipe_xg,            # pipeline object
                   parameters,         # possible parameters
                   n_jobs = 2,         # USe parallel cpu threads
                   cv =2 ,             # No of folds
                   verbose =1,         # Higher the value, more the verbosity
                   scoring = ['accuracy', 'roc_auc'],  # Metrics for performance
                   refit = 'roc_auc'   # Refitting final model on what parameters?
                                       # Those which maximise auc
                   )

In [144]:
X_train.head()

,sku,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,potential_issue,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty,deck_risk,oe_constraint,ppap_risk,stop_auto_buy,rev_stop
1273085,2856024,0.0,12.0,0.0,3.0,3.0,4.0,0.0,0.0,3.0,3.0,0.0,No,0.0,0.73,0.79,0.0,No,No,No,Yes,No
646897,1994878,3.0,8.0,0.0,3.0,6.0,9.0,1.0,4.0,7.0,9.0,1.0,No,0.0,0.87,0.93,0.0,No,No,No,Yes,No
276984,1624972,14.0,10.0,0.0,0.0,8.0,14.0,0.0,10.0,11.0,30.0,0.0,No,0.0,0.80,0.77,0.0,No,No,No,Yes,No
1055771,1415480,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,-99.00,-99.00,0.0,No,No,Yes,Yes,No
261866,1609851,1276.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,No,0.0,0.00,0.00,0.0,No,No,No,No,No

In [146]:
y_train.head()

1273085    0
646897     0
276984     0
1055771    0
261866     0
Name: went_on_backorder, dtype: int32

In [ ]:
df_train.head()

In [ ]:
df_train.info()

In [150]:
X_train = X_train.select_dtypes(include = ['float64', 'int64']).copy()

In [151]:
X_train.head()

,national_inv,lead_time,in_transit_qty,forecast_3_month,forecast_6_month,forecast_9_month,sales_1_month,sales_3_month,sales_6_month,sales_9_month,min_bank,pieces_past_due,perf_6_month_avg,perf_12_month_avg,local_bo_qty
1273085,0.0,12.0,0.0,3.0,3.0,4.0,0.0,0.0,3.0,3.0,0.0,0.0,0.73,0.79,0.0
646897,3.0,8.0,0.0,3.0,6.0,9.0,1.0,4.0,7.0,9.0,1.0,0.0,0.87,0.93,0.0
276984,14.0,10.0,0.0,0.0,8.0,14.0,0.0,10.0,11.0,30.0,0.0,0.0,0.80,0.77,0.0
1055771,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-99.00,-99.00,0.0
261866,1276.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0

In [158]:
X_train = X_train.dropna()

In [159]:
y_train = y_train.dropna()

In [168]:
X_train = X_train.select_dtypes(include = ['float64', 'int64']).copy()